# LAB | Feature Engineering

**Load the data**

In this challenge, we will be working with the same Spaceship Titanic data, like the previous Lab. The data can be found here:

https://raw.githubusercontent.com/data-bootcamp-v4/data/main/spaceship_titanic.csv

Metadata

https://github.com/data-bootcamp-v4/data/blob/main/spaceship_titanic.md

In [3]:
#Libraries
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [4]:
spaceship = pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/data/main/spaceship_titanic.csv")
spaceship.head()

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported
0,0001_01,Europa,False,B/0/P,TRAPPIST-1e,39.0,False,0.0,0.0,0.0,0.0,0.0,Maham Ofracculy,False
1,0002_01,Earth,False,F/0/S,TRAPPIST-1e,24.0,False,109.0,9.0,25.0,549.0,44.0,Juanna Vines,True
2,0003_01,Europa,False,A/0/S,TRAPPIST-1e,58.0,True,43.0,3576.0,0.0,6715.0,49.0,Altark Susent,False
3,0003_02,Europa,False,A/0/S,TRAPPIST-1e,33.0,False,0.0,1283.0,371.0,3329.0,193.0,Solam Susent,False
4,0004_01,Earth,False,F/1/S,TRAPPIST-1e,16.0,False,303.0,70.0,151.0,565.0,2.0,Willy Santantines,True

**Check the shape of your data**

In [6]:
spaceship.shape

(8693, 14)

**Check for data types**

In [8]:
spaceship.dtypes

PassengerId      object
HomePlanet       object
CryoSleep        object
Cabin            object
Destination      object
Age             float64
VIP              object
RoomService     float64
FoodCourt       float64
ShoppingMall    float64
Spa             float64
VRDeck          float64
Name             object
Transported        bool
dtype: object

**Check for missing values**

In [10]:
spaceship.isna().sum()

PassengerId       0
HomePlanet      201
CryoSleep       217
Cabin           199
Destination     182
Age             179
VIP             203
RoomService     181
FoodCourt       183
ShoppingMall    208
Spa             183
VRDeck          188
Name            200
Transported       0
dtype: int64

There are multiple strategies to handle missing data

- Removing all rows or all columns containing missing data.
- Filling all missing values with a value (mean in continouos or mode in categorical for example).
- Filling all missing values with an algorithm.

For this exercise, because we have such low amount of null values, we will drop rows containing any missing value.

In [12]:
spaceship = spaceship.dropna()

- **Cabin** is too granular - transform it in order to obtain {'A', 'B', 'C', 'D', 'E', 'F', 'G', 'T'}

In [14]:
def extract_first_letter(value):
    return value[0]

In [15]:
spaceship["Cabin"] = spaceship["Cabin"].apply(extract_first_letter)

In [16]:
spaceship

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported
0,0001_01,Europa,False,B,TRAPPIST-1e,39.0,False,0.0,0.0,0.0,0.0,0.0,Maham Ofracculy,False
1,0002_01,Earth,False,F,TRAPPIST-1e,24.0,False,109.0,9.0,25.0,549.0,44.0,Juanna Vines,True
2,0003_01,Europa,False,A,TRAPPIST-1e,58.0,True,43.0,3576.0,0.0,6715.0,49.0,Altark Susent,False
3,0003_02,Europa,False,A,TRAPPIST-1e,33.0,False,0.0,1283.0,371.0,3329.0,193.0,Solam Susent,False
4,0004_01,Earth,False,F,TRAPPIST-1e,16.0,False,303.0,70.0,151.0,565.0,2.0,Willy Santantines,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8688,9276_01,Europa,False,A,55 Cancri e,41.0,True,0.0,6819.0,0.0,1643.0,74.0,Gravior Noxnuther,False
8689,9278_01,Earth,True,G,PSO J318.5-22,18.0,False,0.0,0.0,0.0,0.0,0.0,Kurta Mondalley,False
8690,9279_01,Earth,False,G,TRAPPIST-1e,26.0,False,0.0,0.0,1872.0,1.0,0.0,Fayey Connon,True
8691,9280_01,Europa,False,E,55 Cancri e,32.0,False,0.0,1049.0,0.0,353.0,3235.0,Celeon Hontichre,False
8692,9280_02,Europa,False,E,TRAPPIST-1e,44.0,False,126.0,4688.0,0.0,0.0,12.0,Propsh Hontichre,True

- Drop PassengerId and Name

In [18]:
spaceship = spaceship.drop(["PassengerId", "Name"], axis=1)

In [19]:
spaceship

,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Transported
0,Europa,False,B,TRAPPIST-1e,39.0,False,0.0,0.0,0.0,0.0,0.0,False
1,Earth,False,F,TRAPPIST-1e,24.0,False,109.0,9.0,25.0,549.0,44.0,True
2,Europa,False,A,TRAPPIST-1e,58.0,True,43.0,3576.0,0.0,6715.0,49.0,False
3,Europa,False,A,TRAPPIST-1e,33.0,False,0.0,1283.0,371.0,3329.0,193.0,False
4,Earth,False,F,TRAPPIST-1e,16.0,False,303.0,70.0,151.0,565.0,2.0,True
...,...,...,...,...,...,...,...,...,...,...,...,...
8688,Europa,False,A,55 Cancri e,41.0,True,0.0,6819.0,0.0,1643.0,74.0,False
8689,Earth,True,G,PSO J318.5-22,18.0,False,0.0,0.0,0.0,0.0,0.0,False
8690,Earth,False,G,TRAPPIST-1e,26.0,False,0.0,0.0,1872.0,1.0,0.0,True
8691,Europa,False,E,55 Cancri e,32.0,False,0.0,1049.0,0.0,353.0,3235.0,False
8692,Europa,False,E,TRAPPIST-1e,44.0,False,126.0,4688.0,0.0,0.0,12.0,True

- For non-numerical columns, do dummies.

In [21]:
spaceship_dummies = pd.get_dummies(spaceship[["HomePlanet", "CryoSleep", "Cabin", "Destination"]])

In [22]:
spaceship_dummies

,HomePlanet_Earth,HomePlanet_Europa,HomePlanet_Mars,CryoSleep_False,CryoSleep_True,Cabin_A,Cabin_B,Cabin_C,Cabin_D,Cabin_E,Cabin_F,Cabin_G,Cabin_T,Destination_55 Cancri e,Destination_PSO J318.5-22,Destination_TRAPPIST-1e
0,False,True,False,True,False,False,True,False,False,False,False,False,False,False,False,True
1,True,False,False,True,False,False,False,False,False,False,True,False,False,False,False,True
2,False,True,False,True,False,True,False,False,False,False,False,False,False,False,False,True
3,False,True,False,True,False,True,False,False,False,False,False,False,False,False,False,True
4,True,False,False,True,False,False,False,False,False,False,True,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8688,False,True,False,True,False,True,False,False,False,False,False,False,False,True,False,False
8689,True,False,False,False,True,False,False,False,False,False,False,True,False,False,True,False
8690,True,False,False,True,False,False,False,False,False,False,False,True,False,False,False,True
8691,False,True,False,True,False,False,False,False,False,True,False,False,False,True,False,False
8692,False,True,False,True,False,False,False,False,False,True,False,False,False,False,False,True

**Perform Train Test Split**

In [24]:
features_numerical = spaceship.select_dtypes(include=["number"])

In [25]:
features_numerical

       Age  RoomService  FoodCourt  ShoppingMall     Spa  VRDeck
0     39.0          0.0        0.0           0.0     0.0     0.0
1     24.0        109.0        9.0          25.0   549.0    44.0
2     58.0         43.0     3576.0           0.0  6715.0    49.0
3     33.0          0.0     1283.0         371.0  3329.0   193.0
4     16.0        303.0       70.0         151.0   565.0     2.0
...    ...          ...        ...           ...     ...     ...
8688  41.0          0.0     6819.0           0.0  1643.0    74.0
8689  18.0          0.0        0.0           0.0     0.0     0.0
8690  26.0          0.0        0.0        1872.0     1.0     0.0
8691  32.0          0.0     1049.0           0.0   353.0  3235.0
8692  44.0        126.0     4688.0           0.0     0.0    12.0

[6606 rows x 6 columns]

In [26]:
# Concatenate FEATURES (merge dfs "features_numerical" and "spaceship_dummies")

In [27]:
features = pd.concat([features_numerical, spaceship_dummies], axis=1)

In [28]:
features

,Age,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,HomePlanet_Earth,HomePlanet_Europa,HomePlanet_Mars,CryoSleep_False,...,Cabin_B,Cabin_C,Cabin_D,Cabin_E,Cabin_F,Cabin_G,Cabin_T,Destination_55 Cancri e,Destination_PSO J318.5-22,Destination_TRAPPIST-1e
0,39.0,0.0,0.0,0.0,0.0,0.0,False,True,False,True,...,True,False,False,False,False,False,False,False,False,True
1,24.0,109.0,9.0,25.0,549.0,44.0,True,False,False,True,...,False,False,False,False,True,False,False,False,False,True
2,58.0,43.0,3576.0,0.0,6715.0,49.0,False,True,False,True,...,False,False,False,False,False,False,False,False,False,True
3,33.0,0.0,1283.0,371.0,3329.0,193.0,False,True,False,True,...,False,False,False,False,False,False,False,False,False,True
4,16.0,303.0,70.0,151.0,565.0,2.0,True,False,False,True,...,False,False,False,False,True,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8688,41.0,0.0,6819.0,0.0,1643.0,74.0,False,True,False,True,...,False,False,False,False,False,False,False,True,False,False
8689,18.0,0.0,0.0,0.0,0.0,0.0,True,False,False,False,...,False,False,False,False,False,True,False,False,True,False
8690,26.0,0.0,0.0,1872.0,1.0,0.0,True,False,False,True,...,False,False,False,False,False,True,False,False,False,True
8691,32.0,0.0,1049.0,0.0,353.0,3235.0,False,True,False,True,...,False,False,False,True,False,False,False,True,False,False
8692,44.0,126.0,4688.0,0.0,0.0,12.0,False,True,False,True,...,False,False,False,True,False,False,False,False,False,True

In [29]:
target = spaceship["Transported"]

In [30]:
target

0       False
1        True
2       False
3       False
4        True
        ...
8688    False
8689    False
8690     True
8691    False
8692     True
Name: Transported, Length: 6606, dtype: bool

In [31]:
X_train, X_test, y_train, y_test = train_test_split(features, target, test_size = 0.20, random_state=42)

In [32]:
X_train.head()

,Age,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,HomePlanet_Earth,HomePlanet_Europa,HomePlanet_Mars,CryoSleep_False,...,Cabin_B,Cabin_C,Cabin_D,Cabin_E,Cabin_F,Cabin_G,Cabin_T,Destination_55 Cancri e,Destination_PSO J318.5-22,Destination_TRAPPIST-1e
7832,25.0,0.0,1673.0,0.0,642.0,612.0,False,True,False,True,...,False,False,False,False,False,False,False,True,False,False
5842,36.0,0.0,2624.0,1657.0,2799.0,1.0,False,True,False,True,...,False,True,False,False,False,False,False,False,False,True
3928,34.0,0.0,0.0,0.0,0.0,0.0,False,False,True,False,...,False,False,False,False,True,False,False,True,False,False
4091,37.0,0.0,0.0,0.0,0.0,0.0,True,False,False,False,...,False,False,False,False,False,True,False,True,False,False
7679,22.0,0.0,0.0,0.0,0.0,0.0,True,False,False,False,...,False,False,False,False,False,True,False,False,True,False

In [33]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler

In [34]:
normalizer = MinMaxScaler()

In [35]:
normalizer.fit(X_train)

MinMaxScaler()

In [36]:
X_train_norm = normalizer.transform(X_train)

X_test_norm = normalizer.transform(X_test)

In [37]:
X_train

,Age,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,HomePlanet_Earth,HomePlanet_Europa,HomePlanet_Mars,CryoSleep_False,...,Cabin_B,Cabin_C,Cabin_D,Cabin_E,Cabin_F,Cabin_G,Cabin_T,Destination_55 Cancri e,Destination_PSO J318.5-22,Destination_TRAPPIST-1e
7832,25.0,0.0,1673.0,0.0,642.0,612.0,False,True,False,True,...,False,False,False,False,False,False,False,True,False,False
5842,36.0,0.0,2624.0,1657.0,2799.0,1.0,False,True,False,True,...,False,True,False,False,False,False,False,False,False,True
3928,34.0,0.0,0.0,0.0,0.0,0.0,False,False,True,False,...,False,False,False,False,True,False,False,True,False,False
4091,37.0,0.0,0.0,0.0,0.0,0.0,True,False,False,False,...,False,False,False,False,False,True,False,True,False,False
7679,22.0,0.0,0.0,0.0,0.0,0.0,True,False,False,False,...,False,False,False,False,False,True,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4984,31.0,0.0,0.0,0.0,0.0,0.0,False,True,False,False,...,False,False,False,True,False,False,False,True,False,False
6864,22.0,28.0,194.0,2.0,0.0,370.0,True,False,False,True,...,False,False,False,False,True,False,False,False,True,False
6919,25.0,0.0,115.0,0.0,1823.0,4041.0,False,True,False,True,...,False,False,False,False,False,False,False,False,False,True
7137,40.0,0.0,21.0,0.0,1503.0,1392.0,False,True,False,True,...,False,False,False,False,False,False,False,True,False,False
1162,27.0,0.0,0.0,863.0,33.0,2.0,True,False,False,True,...,False,False,False,False,True,False,False,False,False,True

In [38]:
X_train_norm

array([[3.16455696e-01, 0.00000000e+00, 5.61164593e-02, ...,
        1.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [4.55696203e-01, 0.00000000e+00, 8.80152953e-02, ...,
        0.00000000e+00, 0.00000000e+00, 1.00000000e+00],
       [4.30379747e-01, 0.00000000e+00, 0.00000000e+00, ...,
        1.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       ...,
       [3.16455696e-01, 0.00000000e+00, 3.85737765e-03, ...,
        0.00000000e+00, 0.00000000e+00, 1.00000000e+00],
       [5.06329114e-01, 0.00000000e+00, 7.04390702e-04, ...,
        1.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [3.41772152e-01, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 1.00000000e+00]])

In [39]:
X_train.describe()

,Age,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck
count,5284.000000,5284.000000,5284.000000,5284.000000,5284.000000,5284.000000
mean,28.872067,224.404807,488.623959,180.931681,305.745836,310.682816
std,14.465213,641.058124,1705.578218,598.104904,1117.380604,1173.704928
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,19.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,27.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,38.000000,56.000000,83.250000,30.000000,63.000000,44.000000
max,79.000000,8586.000000,29813.000000,12253.000000,22408.000000,20336.000000

In [40]:
X_train_norm.describe()

AttributeError: 'numpy.ndarray' object has no attribute 'describe'

In [41]:
# Convert NumPy array to DataFrame
X_train_norm_df = pd.DataFrame(X_train_norm)

In [43]:
X_train_norm.describe()

AttributeError: 'numpy.ndarray' object has no attribute 'describe'

In [ ]:
X_train_norm = pd.DataFrame(X_train_norm, columns = X_train.columns)
X_train_norm.head()

In [ ]:
X_test_norm = pd.DataFrame(X_test_norm, columns = X_test.columns)
X_test_norm.head()

**Model Selection**

In this exercise we will be using **KNN** as our predictive model.

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
knn = KNeighborsClassifier()

In [ ]:
knn

In [ ]:
knn.fit(X_train_norm, y_train)

In [ ]:
knn.score(X_test_norm, y_test)

- Evaluate your model's performance. Comment it

In [ ]:
pred = knn.predict(X_test)
pred

In [ ]:
y_test.values

In [ ]:
accuracy = knn.score(X_test, y_test)
accuracy

In [ ]:
# The accuracy here is higher than the one obtained in lab-intro_to_ml (accuracy was 0.7715582450832073).
# This is due to us including the columns with string values & converting them into dummies. This feeds more data into the model and increases accuracy.